#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d             7 8 9

bspc config border_width        0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#073642"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar_transparent/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
#nitrogen --restore &
feh --bg-fill /home/kshgrk/background/wall8.jpg
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

#brightness
brightnessctl set 15%
xgamma -gamma 0.85

#clipboard
#greenclip daemon

#enable touchpad natural scrolling
xinput --set-prop 16 "libinput Natural Scrolling Enabled" 1

#optimization
sudo hdparm -B 1 /dev/sda && sudo ryzenadj -f 60
