#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d             7 8 9

bspc config border_width        0
bspc config window_gap          8

bspc config left_padding 20
#bspc config bottom_padding 20
#bspc config top_padding 20
bspc config right_padding 20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config bottom_padding 5
bspc rule -a Pavucontrol state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Blueberry.py state=floating
bspc rule -a Pulseeffects state=floating
bspc rule -a Pulseeffects desktop='^9'
# Border
# bspc config focused_border_color        "#b7bcc4"
# bspc config normal_border_color         "#b7bcc4"
# bspc config active_border_color         "#b7bcc4"
# bspc rule -a firefox state=tiling border=off

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
sh ~/.config/polybar/Murz/launch.sh &
#double_border
#sh ~/.config/Scripts/2bspwm.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
#nitrogen --restore &
feh --bg-fill /home/kshgrk/background/wall27.jpg
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -f --experimental-backend &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

#brightness
brightnessctl set 15%
xgamma -gamma 0.85

#clipboard
# sh ~/.config/bspwm/scripts/clip.sh &

#enable touchpad natural scrolling
xinput --set-prop 16 "libinput Natural Scrolling Enabled" 1

#optimization
sudo hdparm -B 1 /dev/sda

#tear-free
xrandr --output eDP --set TearFree on

#keys-settings
xset r rate 230 30

sudo mount -t ext4 /dev/nvme0n1p5 ~/Media/Endeavour

greenclip daemon
